version: '3.8'

services:
  # Neon Local Proxy Service
  neon-local:
    image: neondatabase/neon_local:latest
    container_name: acquisitions-neon-local
    ports:
      - '5432:5432'
    env_file:
      - .env.development
    networks:
      - acquisitions-dev-network
    healthcheck:
      test: ['CMD', 'pg_isready', '-h', 'localhost', '-p', '5432']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Application Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: acquisitions-app-dev
    ports:
      - '3000:3000'
    env_file:
      - .env.development
    volumes:
      # Mount source code for hot reload in development
      - .:/app
      - /app/node_modules
    depends_on:
      neon-local:
        condition: service_healthy
    networks:
      - acquisitions-dev-network
    restart: unless-stopped

networks:
  acquisitions-dev-network:
    driver: bridge

volumes:
  # Volume for node_modules to improve performance
  node_modules:
